import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ReduxProvider from "@/components/store/ReduxProvider";
import NavBar from "@/components/store/NavBar";
import Script from "next/script";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "SBCEST",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	const messages = useMessages();
	return (
		<ClerkProvider>
			<ReduxProvider>
				<html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
					<head>
						<link
							rel="stylesheet"
							href="https://cdn.moyasar.com/mpf/1.13.0/moyasar.css"
						/>
						<Script src="https://cdn.moyasar.com/mpf/1.13.0/moyasar.js"></Script>
					</head>
					<body className={`${inter.className} `}>
						<Toaster position="top-right" reverseOrder={false} />
						{children}
					</body>
				</html>
			</ReduxProvider>
		</ClerkProvider>
	);
}
